In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/student_exam_performance_dataset.csv")

In [3]:
df.head()

,student_id,gender,age,parental_education,family_income,internet_access,study_environment,study_hours_per_day,attendance_rate,sleep_hours,...,online_courses_completed,tutoring,math_score,reading_score,writing_score,science_score,final_exam_score,previous_gpa,pass_fail,grade_category
0,S00001,Male,17,High School,Medium,Yes,Quiet,2.98,96.5,6.05,...,1,Yes,42.8,62.4,54.8,51.8,49.1,2.44,Fail,F
1,S00002,Female,18,High School,Low,Yes,Quiet,4.45,95.7,6.96,...,0,Yes,77.9,73.5,64.4,61.6,70.1,2.79,Pass,C
2,S00003,Male,17,High School,Medium,No,Quiet,3.75,76.0,7.02,...,4,Yes,53.5,38.3,36.3,47.1,42.2,1.49,Fail,F
3,S00004,Male,18,Bachelor,Medium,Yes,Quiet,2.03,72.6,6.23,...,4,No,28.3,23.5,32.0,39.0,31.9,1.34,Fail,F
4,S00005,Male,18,Bachelor,Medium,Yes,Quiet,5.14,87.3,8.54,...,0,No,74.7,54.9,73.6,55.5,66.4,2.60,Pass,C

In [5]:
df.shape

(10000, 23)

In [6]:
df.columns

Index(['student_id', 'gender', 'age', 'parental_education', 'family_income',
       'internet_access', 'study_environment', 'study_hours_per_day',
       'attendance_rate', 'sleep_hours', 'social_media_hours',
       'assignment_completion_rate', 'participation_score',
       'online_courses_completed', 'tutoring', 'math_score', 'reading_score',
       'writing_score', 'science_score', 'final_exam_score', 'previous_gpa',
       'pass_fail', 'grade_category'],
      dtype='object')

In [10]:
df.dtypes

student_id                     object
gender                         object
age                             int64
parental_education             object
family_income                  object
internet_access                object
study_environment              object
study_hours_per_day           float64
attendance_rate               float64
sleep_hours                   float64
social_media_hours            float64
assignment_completion_rate    float64
participation_score           float64
online_courses_completed        int64
tutoring                       object
math_score                    float64
reading_score                 float64
writing_score                 float64
science_score                 float64
final_exam_score              float64
previous_gpa                  float64
pass_fail                      object
grade_category                 object
dtype: object

In [11]:
df.isna()

,student_id,gender,age,parental_education,family_income,internet_access,study_environment,study_hours_per_day,attendance_rate,sleep_hours,...,online_courses_completed,tutoring,math_score,reading_score,writing_score,science_score,final_exam_score,previous_gpa,pass_fail,grade_category
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [16]:
from sklearn.preprocessing import LabelEncoder

cat_cols = df.select_dtypes(include=['object']).columns.tolist()
if 'student_id' in cat_cols: cat_cols.remove('student_id')

print(f'Categorical columns to encode: {cat_cols}')

df_encoded = pd.get_dummies(df, columns=['gender', 'parental_education', 'family_income', 'internet_access', 'study_environment', 'tutoring'], drop_first=True)

le = LabelEncoder()
df_encoded['pass_fail'] = le.fit_transform(df['pass_fail'])
df_encoded['grade_category_encoded'] = le.fit_transform(df['grade_category'])

display(df_encoded.head())

Categorical columns to encode: ['gender', 'parental_education', 'family_income', 'internet_access', 'study_environment', 'tutoring', 'pass_fail', 'grade_category']

,student_id,age,study_hours_per_day,attendance_rate,sleep_hours,social_media_hours,assignment_completion_rate,participation_score,online_courses_completed,math_score,...,parental_education_High School,parental_education_Master,parental_education_PhD,family_income_Low,family_income_Medium,internet_access_Yes,study_environment_Noisy,study_environment_Quiet,tutoring_Yes,grade_category_encoded
0,S00001,17,2.98,96.5,6.05,0.1,80.5,68.7,1,42.8,...,True,False,False,False,True,True,False,True,True,4
1,S00002,18,4.45,95.7,6.96,2.9,70.9,92.6,0,77.9,...,True,False,False,True,False,True,False,True,True,2
2,S00003,17,3.75,76.0,7.02,2.4,77.6,45.8,4,53.5,...,True,False,False,False,True,False,False,True,True,4
3,S00004,18,2.03,72.6,6.23,3.5,63.5,72.9,4,28.3,...,False,False,False,False,True,True,False,True,False,4
4,S00005,18,5.14,87.3,8.54,2.1,71.8,55.7,0,74.7,...,False,False,False,False,True,True,False,True,False,2

In [17]:
print(f'New shape after encoding: {df_encoded.shape}')

New shape after encoding: (10000, 28)

In [18]:
features = ['age', 'study_hours_per_day', 'attendance_rate', 'sleep_hours', 'participation_score', 'previous_gpa']

X = df_encoded[features]
y = df_encoded['final_exam_score']

print('Selected Features:')
display(X.head())
print(f'\nTarget Variable: final_exam_score')

Selected Features:

,age,study_hours_per_day,attendance_rate,sleep_hours,participation_score,previous_gpa
0,17,2.98,96.5,6.05,68.7,2.44
1,18,4.45,95.7,6.96,92.6,2.79
2,17,3.75,76.0,7.02,45.8,1.49
3,18,2.03,72.6,6.23,72.9,1.34
4,18,5.14,87.3,8.54,55.7,2.60

Target Variable: final_exam_score

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f'Training set size: {X_train.shape}')
print(f'Testing set size: {X_test.shape}')

Training set size: (8000, 6)
Testing set size: (2000, 6)

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)


mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse:.2f}')
print(f'R-squared Score: {r2:.2f}')

Mean Squared Error: 26.87
R-squared Score: 0.82

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=features)
display(X_train_scaled_df.head())

print('Standard Scaling applied to training and testing sets.')

,age,study_hours_per_day,attendance_rate,sleep_hours,participation_score,previous_gpa
0,-0.449671,-0.393235,0.892968,-0.121358,-0.090480,0.881273
1,0.442091,1.337325,0.169283,0.142024,1.554713,-0.188527
2,-0.449671,0.599292,0.347582,0.749829,-0.008561,1.379283
3,0.442091,-1.402728,-0.124386,1.489325,-0.609296,-0.889430
4,-1.341433,2.474066,-0.271221,0.476317,2.053049,1.692844

Standard Scaling applied to training and testing sets.

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_class = df_encoded['pass_fail']

_, _, y_train_class, y_test_class = train_test_split(X, y_class, test_size=0.2, random_state=42)

log_reg = LogisticRegression()
log_reg.fit(X_train_scaled, y_train_class)

y_pred_class = log_reg.predict(X_test_scaled)

accuracy = accuracy_score(y_test_class, y_pred_class)
print(f'Accuracy Score: {accuracy:.2f}')
print('\nClassification Report:')
print(classification_report(y_test_class, y_pred_class))

Accuracy Score: 0.86

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.87      0.87      1070
           1       0.85      0.84      0.85       930

    accuracy                           0.86      2000
   macro avg       0.86      0.86      0.86      2000
weighted avg       0.86      0.86      0.86      2000

In [24]:
log_reg.fit(X_train_scaled, y_train_class)
print('Logistic Regression model has been successfully fitted on the training data.')

Logistic Regression model has been successfully fitted on the training data.